name: CI Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Manual trigger option

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Install dependencies
      - name: Install dependencies
        run: ./project-folder/gradlew dependencies

      # Build the project
      - name: Build project
        run: ./project-folder/gradlew build

      # Run tests
      - name: Run tests
        run: ./project-folder/gradlew test

      # Commit and push changes if there are updates
      - name: Commit and push updates
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automated update by CI workflow"
          git push
        continue-on-error: true
